name: timeline_tile
description: A package to help you build highly customisable timelines with Flutter.
version: 1.0.0
author: Julio Bitencourt <julio.henrique.b@gmail.com>
repository: https://github.com/JHBitencourt/timeline_tile
homepage: https://github.com/JHBitencourt/timeline_tile

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
